"use client";

import { useState } from "react";
import {
  AXES,
  type Brand,
  FONT_NAMES,
  type HSL,
  HARMONIES,
  TONES,
  VIOLATIONS,
  type ViolationId,
  cmyk,
  contrast,
  hex,
  hslToRgb,
  inkOn,
} from "./engine";
import { PersonalityBar } from "./levels/Personality";
import { TypeSpecimen } from "./levels/TypeLab";
import { Lockup, Mark } from "./Logo";
import { MOCKUPS, SocialPost } from "./Mockups";

export function tokens(b: Brand) {
  const p = b.palette!;
  const t = b.pairing!;
  const sizes = [0, 1, 2, 3, 4].map((k) => +(Math.pow(b.scale, k)).toFixed(3));
  return {
    name: b.brief.name,
    color: {
      primary: hex(p.primary),
      secondary: hex(p.secondary),
      accent: hex(p.accent),
      ink: hex(p.dark),
      paper: hex(p.light),
    },
    font: {
      heading: { family: FONT_NAMES[t.heading], weight: t.headingWeight },
      body: { family: FONT_NAMES[t.body], weight: 400 },
    },
    typeScale: { ratio: b.scale, body: "1rem", h3: `${sizes[1]}rem`, h2: `${sizes[2]}rem`, h1: `${sizes[3]}rem`, display: `${sizes[4]}rem` },
    logo: b.logo,
    voice: b.voice?.tone,
  };
}

export function cssVars(b: Brand) {
  const t = tokens(b);
  const slug = b.brief.name.toLowerCase();
  return `:root {
  /* ${b.brief.name} — generated by Brand Forge */
  --${slug}-primary: ${t.color.primary};
  --${slug}-secondary: ${t.color.secondary};
  --${slug}-accent: ${t.color.accent};
  --${slug}-ink: ${t.color.ink};
  --${slug}-paper: ${t.color.paper};

  --${slug}-font-heading: "${t.font.heading.family}", sans-serif;
  --${slug}-font-body: "${t.font.body.family}", sans-serif;
  --${slug}-heading-weight: ${t.font.heading.weight};

  --${slug}-text-body: ${t.typeScale.body};
  --${slug}-text-h3: ${t.typeScale.h3};
  --${slug}-text-h2: ${t.typeScale.h2};
  --${slug}-text-h1: ${t.typeScale.h1};
  --${slug}-text-display: ${t.typeScale.display};
}`;
}

function download(name: string, text: string, type: string) {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function GuidelineActions({ b }: { b: Brand }) {
  const [copied, setCopied] = useState("");
  const copy = async (label: string, text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(label);
      setTimeout(() => setCopied(""), 1600);
    } catch {
      setCopied("Copy failed");
    }
  };
  const slug = b.brief.name.toLowerCase();
  const btn = "rounded-full border border-ink/15 bg-white/70 px-4 py-2 text-xs font-semibold text-ink transition hover:bg-ink hover:text-paper";
  return (
    <div className="bf-no-print flex flex-wrap gap-2">
      <button className={btn} onClick={() => window.print()}>
        ⎙ Save as PDF
      </button>
      <button className={btn} onClick={() => download(`${slug}-tokens.json`, JSON.stringify(tokens(b), null, 2), "application/json")}>
        ⇩ Design tokens (JSON)
      </button>
      <button className={btn} onClick={() => download(`${slug}-variables.css`, cssVars(b), "text/css")}>
        ⇩ CSS variables
      </button>
      <button className={btn} onClick={() => copy("Brief code copied", b.brief.seed)}>
        ⧉ Copy brief code
      </button>
      {copied && <span className="self-center text-xs text-ink/60">{copied}</span>}
    </div>
  );
}

const Section = ({ n, title, children, intro }: { n: string; title: string; intro?: string; children: React.ReactNode }) => (
  <section className="bf-page border-t border-ink/10 py-14 sm:py-20">
    <div className="grid gap-8 lg:grid-cols-[220px_1fr]">
      <div>
        <p className="font-display text-6xl leading-none text-ink/15">{n}</p>
        <h3 className="mt-2 font-display text-4xl leading-none">{title}</h3>
        {intro && <p className="mt-4 text-sm leading-relaxed text-ink/60">{intro}</p>}
      </div>
      <div className="min-w-0">{children}</div>
    </div>
  </section>
);

export default function Guideline({ b }: { b: Brand }) {
  const p = b.palette!;
  const t = b.pairing!;
  const name = b.brief.name;
  const C = {
    primary: hex(p.primary),
    secondary: hex(p.secondary),
    accent: hex(p.accent),
    dark: hex(p.dark),
    light: hex(p.light),
  };
  const lock = { spec: b.logo!, name, font: t.heading, weight: t.headingWeight };
  const tone = TONES[b.voice?.tone ?? "warm"];
  const swatches: [string, HSL, string][] = [
    ["Primary", p.primary, "Hero colour. Logos, key actions, big moments."],
    ["Secondary", p.secondary, "Supporting surfaces, illustrations, charts."],
    ["Accent", p.accent, "Sparingly — highlights, badges, calls to action."],
    ["Ink", p.dark, "Text and dark surfaces."],
    ["Paper", p.light, "Backgrounds and breathing room."],
  ];

  return (
    <article className="bf-guide rounded-[2rem] bg-[#FBFAF7] text-ink shadow-[0_30px_80px_-30px_rgba(0,0,0,0.5)]">
      {/* Cover */}
      <div className="bf-page relative flex min-h-[70vh] flex-col justify-between overflow-hidden rounded-t-[2rem] p-8 sm:p-14" style={{ background: C.primary, color: inkOn(C.primary, C.dark, C.light) }}>
        <div className="absolute -right-24 -bottom-24 size-96 rounded-full opacity-90" style={{ background: C.accent }} />
        <div className="absolute right-24 bottom-40 size-40 rounded-full" style={{ background: C.secondary }} />
        <p className="relative text-xs tracking-[0.3em] uppercase opacity-80">Brand Guidelines · v1.0</p>
        <div className="relative">
          <Lockup layout={b.lockup} {...lock} fg={inkOn(C.primary, C.dark, C.light)} bg={C.primary} height={96} />
          <p className="mt-8 max-w-lg text-xl sm:text-2xl" style={{ fontFamily: `var(--bf-${t.body})` }}>
            {b.brief.tagline}
          </p>
        </div>
        <p className="relative text-xs opacity-70">
          Brief {b.brief.seed} · {b.brief.industry} · Made with Brand Forge
        </p>
      </div>

      <div className="px-6 sm:px-14">
        <Section n="01" title="Brand story" intro="Who we are and why we exist.">
          <p className="font-display text-3xl leading-tight sm:text-4xl">
            {name} is a {b.brief.industry.toLowerCase()} making {b.brief.product} for {b.brief.audience}.
          </p>
          <div className="mt-10 grid gap-6 sm:grid-cols-3">
            {b.brief.values.map((v, i) => (
              <div key={v} className="rounded-2xl p-5" style={{ background: i === 0 ? C.primary : i === 1 ? C.secondary : C.accent, color: inkOn(i === 0 ? C.primary : i === 1 ? C.secondary : C.accent, C.dark, C.light) }}>
                <p className="text-xs uppercase opacity-70">Value 0{i + 1}</p>
                <p className="mt-6 text-2xl" style={{ fontFamily: `var(--bf-${t.heading})`, fontWeight: t.headingWeight }}>
                  {v}
                </p>
              </div>
            ))}
          </div>
          <div className="mt-10 grid gap-4">
            <p className="text-xs tracking-widest text-ink/50 uppercase">Personality</p>
            {AXES.map((a) => (
              <PersonalityBar key={a} axis={a} value={b.vec[a]} light />
            ))}
          </div>
        </Section>

        <Section n="02" title="Logo" intro="Our most recognisable asset. Treat it with care.">
          <div className="grid gap-3 sm:grid-cols-3">
            {[
              { bg: C.light, fg: C.primary, w: C.dark, label: "Primary — on paper" },
              { bg: C.primary, fg: inkOn(C.primary, C.dark, C.light), w: inkOn(C.primary, C.dark, C.light), label: "Reversed — on primary" },
              { bg: C.dark, fg: C.light, w: C.light, label: "Mono — on ink" },
            ].map((s) => (
              <figure key={s.label}>
                <div className="grid aspect-[4/3] place-items-center rounded-2xl ring-1 ring-ink/10" style={{ background: s.bg }}>
                  <Lockup layout={b.lockup} {...lock} fg={s.fg} bg={s.bg} wordColor={s.w} height={40} />
                </div>
                <figcaption className="mt-2 text-xs text-ink/60">{s.label}</figcaption>
              </figure>
            ))}
          </div>
          <div className="mt-8 grid gap-6 sm:grid-cols-2">
            <div className="rounded-2xl bg-white p-6 ring-1 ring-ink/10">
              <p className="text-xs tracking-widest text-ink/50 uppercase">Clear space</p>
              <div className="mt-6 grid place-items-center">
                <div className="relative border border-dashed p-6" style={{ borderColor: C.accent }}>
                  <span className="absolute top-1 left-1/2 -translate-x-1/2 text-[10px] font-semibold" style={{ color: C.accent }}>
                    x
                  </span>
                  <span className="absolute top-1/2 left-1 -translate-y-1/2 text-[10px] font-semibold" style={{ color: C.accent }}>
                    x
                  </span>
                  <Mark {...lock} fg={C.primary} bg={C.light} size={72} />
                </div>
              </div>
              <p className="mt-4 text-sm text-ink/60">Keep a margin of at least <strong>x</strong> — a quarter of the mark&apos;s height — on every side.</p>
            </div>
            <div className="rounded-2xl bg-white p-6 ring-1 ring-ink/10">
              <p className="text-xs tracking-widest text-ink/50 uppercase">Minimum size</p>
              <div className="mt-6 flex items-end justify-center gap-6">
                {[64, 40, 24, 16].map((s) => (
                  <div key={s} className="flex flex-col items-center gap-2">
                    <Mark {...lock} fg={C.primary} bg={C.light} size={s} />
                    <span className="text-[10px] text-ink/50">{s}px</span>
                  </div>
                ))}
              </div>
              <p className="mt-4 text-sm text-ink/60">Never smaller than <strong>24px</strong> on screen or <strong>12mm</strong> in print. Use the mark alone below 120px wide.</p>
            </div>
          </div>
          <p className="mt-10 text-xs tracking-widest text-ink/50 uppercase">Don&apos;t</p>
          <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
            {(Object.keys(VIOLATIONS) as ViolationId[]).map((v) => (
              <figure key={v}>
                <div className="relative aspect-square overflow-hidden rounded-2xl">
                  <SocialPost b={b} v={v} />
                  <span className="absolute top-2 right-2 grid size-6 place-items-center rounded-full bg-[#E5484D] text-xs font-bold text-white">✕</span>
                </div>
                <figcaption className="mt-2 text-xs leading-snug text-ink/70">
                  {VIOLATIONS[v].rule}
                  {b.donts.includes(v) && <span className="ml-1 text-[#2F9E5B]">· caught in review</span>}
                </figcaption>
              </figure>
            ))}
          </div>
        </Section>

        <Section n="03" title="Colour" intro={`A ${HARMONIES.find((h) => h.id === p.harmony)?.label.toLowerCase()} palette built around one hero colour.`}>
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
            {swatches.map(([label, c, use], i) => {
              const h = hex(c);
              const rgb = hslToRgb(c);
              return (
                <div key={label} className={`overflow-hidden rounded-2xl ring-1 ring-ink/10 ${i === 0 ? "col-span-2" : ""}`}>
                  <div className="flex aspect-[4/3] items-end p-4 text-sm font-semibold" style={{ background: h, color: inkOn(h, C.dark, C.light) }}>
                    {label}
                  </div>
                  <dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-0.5 bg-white p-3 text-[11px]">
                    <dt className="text-ink/40">HEX</dt>
                    <dd className="font-mono">{h}</dd>
                    <dt className="text-ink/40">RGB</dt>
                    <dd className="font-mono">{rgb.join(" ")}</dd>
                    <dt className="text-ink/40">CMYK</dt>
                    <dd className="font-mono">{cmyk(rgb).join(" ")}</dd>
                    <dt className="text-ink/40">HSL</dt>
                    <dd className="font-mono">
                      {Math.round(c.h)} {Math.round(c.s)}% {Math.round(c.l)}%
                    </dd>
                  </dl>
                  <p className="bg-white px-3 pb-3 text-[11px] leading-snug text-ink/60">{use}</p>
                </div>
              );
            })}
          </div>
          <p className="mt-10 text-xs tracking-widest text-ink/50 uppercase">Proportion</p>
          <div className="mt-3 flex h-12 overflow-hidden rounded-2xl ring-1 ring-ink/10">
            <div style={{ flex: 55, background: C.light }} />
            <div style={{ flex: 25, background: C.primary }} />
            <div style={{ flex: 12, background: C.dark }} />
            <div style={{ flex: 6, background: C.secondary }} />
            <div style={{ flex: 2, background: C.accent }} />
          </div>
          <p className="mt-10 text-xs tracking-widest text-ink/50 uppercase">Accessible pairings</p>
          <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">
            {[
              [C.dark, C.light],
              [C.light, C.dark],
              [C.light, C.primary],
              [C.dark, C.primary],
              [C.dark, C.accent],
              [C.light, C.accent],
              [C.primary, C.light],
              [C.dark, C.secondary],
            ].map(([fg, bg]) => {
              const r = contrast(fg, bg);
              const badge = r >= 7 ? "AAA" : r >= 4.5 ? "AA" : r >= 3 ? "Large only" : "Fail";
              return (
                <div key={fg + bg} className="flex items-center justify-between rounded-xl p-3 ring-1 ring-ink/10" style={{ background: bg, color: fg }}>
                  <span className="text-lg font-semibold">Aa</span>
                  <span className="text-[10px] font-semibold">
                    {r.toFixed(1)} · {badge}
                  </span>
                </div>
              );
            })}
          </div>
        </Section>

        <Section n="04" title="Typography" intro={`${FONT_NAMES[t.heading]} for headlines, ${FONT_NAMES[t.body]} for everything else. Scale ratio ${b.scale}.`}>
          <TypeSpecimen pairing={t} scale={b.scale} name={name} tagline={b.brief.tagline} light />
          <ul className="mt-6 grid gap-2 text-sm text-ink/70 sm:grid-cols-2">
            <li>• Headlines: sentence case, tight leading (1.05–1.15).</li>
            <li>• Body: 16px minimum, 1.5–1.6 line height.</li>
            <li>• Max line length ~70 characters.</li>
            <li>• Never fake bold or italic, never outline type.</li>
          </ul>
        </Section>

        <Section n="05" title="Voice" intro={`Our tone is ${tone.label.toLowerCase()}. It flexes by moment, never by personality.`}>
          <div className="grid gap-3 sm:grid-cols-2">
            <div className="rounded-2xl p-6" style={{ background: C.primary, color: inkOn(C.primary, C.dark, C.light) }}>
              <p className="text-xs uppercase opacity-70">We are</p>
              {tone.weAre.map((w) => (
                <p key={w} className="text-3xl" style={{ fontFamily: `var(--bf-${t.heading})`, fontWeight: t.headingWeight }}>
                  {w}
                </p>
              ))}
            </div>
            <div className="rounded-2xl bg-white p-6 ring-1 ring-ink/10">
              <p className="text-xs text-ink/50 uppercase">We are not</p>
              {tone.weAreNot.map((w) => (
                <p key={w} className="text-3xl text-ink/40 line-through" style={{ fontFamily: `var(--bf-${t.heading})`, fontWeight: t.headingWeight, textDecorationColor: C.accent }}>
                  {w}
                </p>
              ))}
            </div>
          </div>
          {b.voice && b.voice.samples.length > 0 && (
            <div className="mt-8 grid gap-3">
              <p className="text-xs tracking-widest text-ink/50 uppercase">In the wild</p>
              {b.voice.samples.map((s) => (
                <div key={s.label} className="grid gap-1 rounded-2xl bg-white p-4 ring-1 ring-ink/10 sm:grid-cols-[200px_1fr]">
                  <span className="text-xs text-ink/50">{s.label}</span>
                  <span style={{ fontFamily: `var(--bf-${t.body})` }}>{s.text}</span>
                </div>
              ))}
            </div>
          )}
        </Section>

        <Section n="06" title="Applications" intro="The system, out in the world.">
          <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
            {MOCKUPS.map((m) => (
              <figure key={m.id}>
                <div className={`overflow-hidden rounded-2xl ring-1 ring-ink/10 ${m.aspect}`}>
                  <m.C b={b} />
                </div>
                <figcaption className="mt-2 text-xs text-ink/60">{m.label}</figcaption>
              </figure>
            ))}
          </div>
        </Section>

        <Section n="07" title="Design tokens" intro="Drop these straight into code.">
          <pre className="overflow-x-auto rounded-2xl bg-ink p-5 text-xs leading-relaxed text-paper">
            <code>{cssVars(b)}</code>
          </pre>
        </Section>
      </div>
      <div className="bf-page rounded-b-[2rem] px-6 py-10 text-center text-xs text-ink/50 sm:px-14">
        {name} Brand Guidelines · Generated with Brand Forge by Satish Kumar
      </div>
    </article>
  );
}
